<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/db.php';exigirLogin();
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('Método não permitido.');}
$ctx=(string)($_SESSION['contexto']??'');$admin=$ctx==='administrador';$prof=$ctx==='profissional';if(!$admin&&!$prof)negarAcesso();
$csrf=(string)($_POST['csrf_token']??'');$cs=(string)($_SESSION['csrf_ausencias_profissionais']??'');if(!$csrf||!$cs||!hash_equals($cs,$csrf)){http_response_code(403);exit('Token CSRF inválido.');}
$e=(int)$_SESSION['empresa_id'];$u=(int)$_SESSION['user_id'];$p=(int)($_SESSION['profissional_id']??0);$acao=(string)($_POST['acao']??'');$pdo=getDB();
function red(?int$id=null):never{header('Location: ../ausencias-profissionais.php'.($id?'?detalhe='.$id:''));exit;}function ok(string$m,?int$id=null):never{$_SESSION['flash_success']=$m;red($id);}function fal(string$m,?int$id=null):never{$_SESSION['flash_error']=$m;red($id);}
function hist(PDO$p,int$s,int$u,string$a,string$d=''):void{$q=$p->prepare('INSERT INTO profissional_solicitacao_ausencia_historico(solicitacao_id,usuario_id,acao,detalhes)VALUES(:s,:u,:a,:d)');$q->execute([':s'=>$s,':u'=>$u,':a'=>$a,':d'=>$d?:null]);}
function sol(PDO$p,int$id,int$e,bool$lock=false):?array{$q=$p->prepare("SELECT s.*,pe.nome_completo profissional_nome FROM profissional_solicitacoes_ausencia s INNER JOIN profissionais pr ON pr.id=s.profissional_id AND pr.empresa_id=s.empresa_id INNER JOIN pessoas pe ON pe.id=pr.pessoa_id AND pe.empresa_id=s.empresa_id WHERE s.id=:id AND s.empresa_id=:e LIMIT 1".($lock?' FOR UPDATE':''));$q->execute([':id'=>$id,':e'=>$e]);$r=$q->fetch(PDO::FETCH_ASSOC);return$r?:null;}
if($acao==='solicitar'){if(!$prof||$p<=0)negarAcesso();$tipos=['pausa','almoco','folga','falta','atestado','ferias','compromisso','treinamento','emergencial','outro'];$t=(string)($_POST['tipo']??'');try{$i=new DateTimeImmutable((string)$_POST['inicio']);$f=new DateTimeImmutable((string)$_POST['fim']);}catch(Throwable$x){fal('Período inválido.');}if(!in_array($t,$tipos,true)||$f<=$i)fal('Período inválido.');$m=trim((string)($_POST['motivo']??''));$o=trim((string)($_POST['observacao']??''));$pdo->beginTransaction();try{$q=$pdo->prepare('INSERT INTO profissional_solicitacoes_ausencia(empresa_id,profissional_id,inicio,fim,tipo,motivo,observacao,solicitado_por_usuario_id)VALUES(:e,:p,:i,:f,:t,:m,:o,:u)');$q->execute([':e'=>$e,':p'=>$p,':i'=>$i->format('Y-m-d H:i:s'),':f'=>$f->format('Y-m-d H:i:s'),':t'=>$t,':m'=>$m?:null,':o'=>$o?:null,':u'=>$u]);$id=(int)$pdo->lastInsertId();hist($pdo,$id,$u,'SOLICITOU',$m);$pdo->commit();ok('Solicitação enviada para análise.',$id);}catch(Throwable$x){if($pdo->inTransaction())$pdo->rollBack();throw$x;}}
$id=filter_input(INPUT_POST,'solicitacao_id',FILTER_VALIDATE_INT);if(!is_int($id)||$id<=0)fal('Solicitação inválida.');
if($acao==='cancelar_pendente'){if(!$prof)negarAcesso();$pdo->beginTransaction();try{$s=sol($pdo,$id,$e,true);if(!$s||(int)$s['profissional_id']!==$p){$pdo->rollBack();negarAcesso();}if($s['status']!=='pendente'){$pdo->rollBack();fal('Somente solicitação pendente pode ser cancelada.',$id);}$pdo->prepare("UPDATE profissional_solicitacoes_ausencia SET status='cancelada' WHERE id=:id")->execute([':id'=>$id]);hist($pdo,$id,$u,'CANCELOU_SOLICITACAO');$pdo->commit();ok('Solicitação cancelada.',$id);}catch(Throwable$x){if($pdo->inTransaction())$pdo->rollBack();throw$x;}}
if(!$admin)negarAcesso();
if($acao==='comentar'){$c=trim((string)($_POST['comentario']??''));if(!$c)fal('Informe o comentário.',$id);if(!sol($pdo,$id,$e))negarAcesso();$pdo->prepare('INSERT INTO profissional_solicitacao_ausencia_comentarios(solicitacao_id,usuario_id,comentario)VALUES(:s,:u,:c)')->execute([':s'=>$id,':u'=>$u,':c'=>$c]);ok('Comentário interno adicionado.',$id);}
if($acao==='aprovar'){$obs=trim((string)($_POST['observacao_decisao']??''));$pdo->beginTransaction();try{$s=sol($pdo,$id,$e,true);if(!$s){$pdo->rollBack();negarAcesso();}if($s['status']!=='pendente'){$pdo->rollBack();fal('Solicitação já analisada.',$id);}$q=$pdo->prepare('INSERT INTO profissional_bloqueios(profissional_id,inicio,fim,motivo,criado_por_usuario_id)VALUES(:p,:i,:f,:m,:u)');$q->execute([':p'=>$s['profissional_id'],':i'=>$s['inicio'],':f'=>$s['fim'],':m'=>$s['motivo']?:'Ausência aprovada',':u'=>$u]);$b=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE profissional_solicitacoes_ausencia SET status='aprovada',analisado_por_usuario_id=:u,analisado_em=NOW(),observacao_decisao=:o,bloqueio_id=:b WHERE id=:id")->execute([':u'=>$u,':o'=>$obs?:null,':b'=>$b,':id'=>$id]);hist($pdo,$id,$u,'APROVOU',$obs);$pdo->commit();
try{require_once __DIR__.'/../../services/EmailService.php';$q=$pdo->prepare('SELECT nome_completo,email FROM administradores WHERE empresa_id=:e AND ativo=1 LIMIT 1');$q->execute([':e'=>$e]);$a=$q->fetch(PDO::FETCH_ASSOC);$q=$pdo->prepare('SELECT nome FROM usuarios WHERE id=:u');$q->execute([':u'=>$u]);$aprovadorNome=(string)($q->fetchColumn()?:'Administrador');if($a&&filter_var($a['email'],FILTER_VALIDATE_EMAIL)){$profissionalNome=(string)$s['profissional_nome'];$periodo=(new DateTimeImmutable($s['inicio']))->format('d/m/Y H:i').' – '.(new DateTimeImmutable($s['fim']))->format('d/m/Y H:i');$aprovadoEm=date('d/m/Y H:i');ob_start();require __DIR__.'/../../templates/emails/ausencia-profissional-aprovada.php';$html=(string)ob_get_clean();(new EmailService())->enviar((string)$a['email'],(string)$a['nome_completo'],'Ausência de profissional aprovada — '.$profissionalNome,$html);}}catch(Throwable$x){error_log('E-mail ausência: '.$x->getMessage());}ok('Ausência aprovada e bloqueio aplicado.',$id);}catch(Throwable$x){if($pdo->inTransaction())$pdo->rollBack();throw$x;}}
if($acao==='rejeitar'){$obs=trim((string)($_POST['observacao_decisao']??''));$pdo->beginTransaction();try{$s=sol($pdo,$id,$e,true);if(!$s){$pdo->rollBack();negarAcesso();}if($s['status']!=='pendente'){$pdo->rollBack();fal('Solicitação já analisada.',$id);}$pdo->prepare("UPDATE profissional_solicitacoes_ausencia SET status='rejeitada',analisado_por_usuario_id=:u,analisado_em=NOW(),observacao_decisao=:o WHERE id=:id")->execute([':u'=>$u,':o'=>$obs?:null,':id'=>$id]);hist($pdo,$id,$u,'REJEITOU',$obs);$pdo->commit();ok('Solicitação rejeitada.',$id);}catch(Throwable$x){if($pdo->inTransaction())$pdo->rollBack();throw$x;}}
if($acao==='cancelar_aprovacao'){$m=trim((string)($_POST['motivo_cancelamento']??''));if(!$m)fal('Informe o motivo.',$id);$pdo->beginTransaction();try{$s=sol($pdo,$id,$e,true);if(!$s){$pdo->rollBack();negarAcesso();}if($s['status']!=='aprovada'){$pdo->rollBack();fal('Solicitação não aprovada.',$id);}if($s['bloqueio_id'])$pdo->prepare('DELETE pb FROM profissional_bloqueios pb INNER JOIN profissionais pr ON pr.id=pb.profissional_id WHERE pb.id=:b AND pr.empresa_id=:e')->execute([':b'=>$s['bloqueio_id'],':e'=>$e]);$pdo->prepare("UPDATE profissional_solicitacoes_ausencia SET status='cancelada',bloqueio_id=NULL WHERE id=:id")->execute([':id'=>$id]);hist($pdo,$id,$u,'CANCELOU_APROVACAO',$m);$pdo->commit();ok('Aprovação cancelada; histórico preservado.',$id);}catch(Throwable$x){if($pdo->inTransaction())$pdo->rollBack();throw$x;}}
fal('Ação inválida.',$id);
