<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/auth.php'; require_once __DIR__.'/../../includes/db.php'; exigirCliente(); header('Content-Type: application/json; charset=utf-8');
$pdo=getDB(); $empresaId=(int)$_SESSION['empresa_id']; $clienteId=(int)$_SESSION['cliente_id']; $usuarioId=(int)$_SESSION['user_id'];
function out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE);exit;}
function dv(string $d):bool{$x=DateTimeImmutable::createFromFormat('!Y-m-d',$d);return $x!==false&&$x->format('Y-m-d')===$d;}
function overlap(DateTimeImmutable $a,DateTimeImmutable $b,DateTimeImmutable $c,DateTimeImmutable $d):bool{return $a<$d&&$b>$c;}
function dadosServico(PDO $p,int $e,int $s,int $pr):?array{$q=$p->prepare('SELECT s.nome,s.intervalo_minutos,COALESCE(ps.duracao_minutos,s.duracao_minutos) duracao,COALESCE(ps.preco,s.preco) preco FROM servicos s JOIN profissional_servicos ps ON ps.servico_id=s.id AND ps.profissional_id=:pr AND ps.ativo=1 JOIN profissionais r ON r.id=ps.profissional_id AND r.empresa_id=s.empresa_id AND r.ativo=1 JOIN pessoas pe ON pe.id=r.pessoa_id AND pe.empresa_id=r.empresa_id AND pe.ativo=1 WHERE s.id=:s AND s.empresa_id=:e AND s.ativo=1 AND s.permite_agendamento_online=1 LIMIT 1');$q->execute([':pr'=>$pr,':s'=>$s,':e'=>$e]);$r=$q->fetch(PDO::FETCH_ASSOC);return $r?:null;}
function slots(PDO $p,int $e,int $s,int $pr,string $data,int $ignorar=0):array{
 $sv=dadosServico($p,$e,$s,$pr); if(!$sv||new DateTimeImmutable($data)<new DateTimeImmutable('today'))return[];
 $q=$p->prepare('SELECT id,tipo FROM empresa_excecoes WHERE empresa_id=:e AND data_excecao=:d AND ativo=1 LIMIT 1');$q->execute([':e'=>$e,':d'=>$data]);$ex=$q->fetch(PDO::FETCH_ASSOC);
 if($ex&&$ex['tipo']==='fechado')return[]; $dia=(int)(new DateTimeImmutable($data))->format('N');
 if($ex){$q=$p->prepare('SELECT hora_inicio,hora_fim FROM empresa_excecao_periodos WHERE empresa_excecao_id=:id ORDER BY hora_inicio');$q->execute([':id'=>$ex['id']]);}
 else{$q=$p->prepare('SELECT hora_inicio,hora_fim FROM empresa_horarios WHERE empresa_id=:e AND dia_semana=:dia AND ativo=1 ORDER BY hora_inicio');$q->execute([':e'=>$e,':dia'=>$dia]);}
 $ep=$q->fetchAll(PDO::FETCH_ASSOC); if(!$ep)return[];
 $q=$p->prepare('SELECT hora_inicio,hora_fim FROM profissional_horarios WHERE profissional_id=:pr AND dia_semana=:dia AND ativo=1 ORDER BY hora_inicio');$q->execute([':pr'=>$pr,':dia'=>$dia]);$pp=$q->fetchAll(PDO::FETCH_ASSOC);if(!$pp)return[];
 $di=$data.' 00:00:00';$df=(new DateTimeImmutable($di))->modify('+1 day')->format('Y-m-d H:i:s');
 $q=$p->prepare('SELECT inicio,fim FROM profissional_bloqueios WHERE profissional_id=:pr AND inicio<:df AND fim>:di');$q->execute([':pr'=>$pr,':df'=>$df,':di'=>$di]);$busy=$q->fetchAll(PDO::FETCH_ASSOC);
 $sql="SELECT x.inicio,x.fim FROM agendamento_servicos x JOIN agendamentos a ON a.id=x.agendamento_id WHERE x.profissional_id=:pr AND x.inicio<:df AND x.fim>:di AND a.status NOT IN ('cancelado','nao_compareceu') AND x.status NOT IN ('cancelado','nao_compareceu')";
 $pa=[':pr'=>$pr,':df'=>$df,':di'=>$di]; if($ignorar>0){$sql.=" AND a.id<>:ignorar";$pa[':ignorar']=$ignorar;} $q=$p->prepare($sql);$q->execute($pa);$busy=array_merge($busy,$q->fetchAll(PDO::FETCH_ASSOC));
 $res=[];$dur=(int)$sv['duracao'];$int=(int)$sv['intervalo_minutos'];$now=new DateTimeImmutable();
 foreach($ep as $a)foreach($pp as $b){$i=max(new DateTimeImmutable("$data ".$a['hora_inicio']),new DateTimeImmutable("$data ".$b['hora_inicio']));$f=min(new DateTimeImmutable("$data ".$a['hora_fim']),new DateTimeImmutable("$data ".$b['hora_fim']));for($c=$i;;$c=$c->modify('+15 minutes')){$fs=$c->modify("+$dur minutes");$fr=$fs->modify("+$int minutes");if($fr>$f)break;if($c<=$now)continue;$ok=true;foreach($busy as $o)if(overlap($c,$fr,new DateTimeImmutable($o['inicio']),new DateTimeImmutable($o['fim']))){$ok=false;break;}if($ok)$res[]=['hora'=>$c->format('H:i'),'inicio'=>$c->format('Y-m-d H:i:s'),'fim'=>$fs->format('Y-m-d H:i:s')];}}
 return $res;
}
$a=trim((string)($_GET['acao']??$_POST['acao']??''));
try{
 if($a==='servicos'){$q=$pdo->prepare('SELECT DISTINCT s.id,s.nome FROM servicos s JOIN profissional_servicos ps ON ps.servico_id=s.id AND ps.ativo=1 JOIN profissionais pr ON pr.id=ps.profissional_id AND pr.empresa_id=s.empresa_id AND pr.ativo=1 JOIN pessoas p ON p.id=pr.pessoa_id AND p.ativo=1 WHERE s.empresa_id=:e AND s.ativo=1 AND s.permite_agendamento_online=1 ORDER BY s.nome');$q->execute([':e'=>$empresaId]);out(['ok'=>true,'servicos'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
 if($a==='profissionais'){$s=(int)($_GET['servico_id']??0);$q=$pdo->prepare('SELECT pr.id,p.nome_completo,COALESCE(ps.preco,s.preco) preco FROM profissional_servicos ps JOIN profissionais pr ON pr.id=ps.profissional_id AND pr.ativo=1 JOIN pessoas p ON p.id=pr.pessoa_id AND p.ativo=1 JOIN servicos s ON s.id=ps.servico_id AND s.empresa_id=pr.empresa_id WHERE pr.empresa_id=:e AND ps.servico_id=:s AND ps.ativo=1 AND s.ativo=1 AND s.permite_agendamento_online=1 ORDER BY p.nome_completo');$q->execute([':e'=>$empresaId,':s'=>$s]);out(['ok'=>true,'profissionais'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
 if($a==='horarios'){$s=(int)($_GET['servico_id']??0);$pr=(int)($_GET['profissional_id']??0);$d=trim((string)($_GET['data']??''));$rid=(int)($_GET['reagendar_id']??0);if(!$s||!$pr||!dv($d))out(['ok'=>false,'mensagem'=>'Dados inválidos.'],422);if($rid){$q=$pdo->prepare("SELECT inicio,status FROM agendamentos WHERE id=:id AND empresa_id=:e AND cliente_id=:c");$q->execute([':id'=>$rid,':e'=>$empresaId,':c'=>$clienteId]);$ag=$q->fetch(PDO::FETCH_ASSOC);if(!$ag)out(['ok'=>false,'mensagem'=>'Agendamento não encontrado.'],404);if(!in_array($ag['status'],['pendente','confirmado'],true)||new DateTimeImmutable()>=((new DateTimeImmutable($ag['inicio']))->modify('-2 hours')))out(['ok'=>false,'mensagem'=>'O prazo de 2 horas para alteração terminou.'],409);}out(['ok'=>true,'horarios'=>slots($pdo,$empresaId,$s,$pr,$d,$rid)]);}
 if($a==='detalhe_reagendamento'){$id=(int)($_GET['agendamento_id']??0);$q=$pdo->prepare("SELECT a.inicio,a.status,x.servico_id,x.profissional_id FROM agendamentos a JOIN agendamento_servicos x ON x.agendamento_id=a.id AND x.ordem=1 WHERE a.id=:id AND a.empresa_id=:e AND a.cliente_id=:c LIMIT 1");$q->execute([':id'=>$id,':e'=>$empresaId,':c'=>$clienteId]);$ag=$q->fetch(PDO::FETCH_ASSOC);if(!$ag)out(['ok'=>false,'mensagem'=>'Agendamento não encontrado.'],404);if(!in_array($ag['status'],['pendente','confirmado'],true)||new DateTimeImmutable()>=((new DateTimeImmutable($ag['inicio']))->modify('-2 hours')))out(['ok'=>false,'mensagem'=>'O prazo de 2 horas para alteração terminou.'],409);$dt=new DateTimeImmutable($ag['inicio']);out(['ok'=>true,'agendamento'=>['servico_id'=>(int)$ag['servico_id'],'profissional_id'=>(int)$ag['profissional_id'],'data'=>$dt->format('Y-m-d'),'hora'=>$dt->format('H:i')]]);}
 if($a==='cancelar'){if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'mensagem'=>'Método não permitido.'],405);$csrf=(string)($_POST['csrf_token']??'');$ss=(string)($_SESSION['csrf_autoagendamento']??'');if(!$csrf||!$ss||!hash_equals($ss,$csrf))out(['ok'=>false,'mensagem'=>'Token CSRF inválido.'],403);$id=(int)($_POST['agendamento_id']??0);$pdo->beginTransaction();$q=$pdo->prepare("SELECT inicio,status FROM agendamentos WHERE id=:id AND empresa_id=:e AND cliente_id=:c FOR UPDATE");$q->execute([':id'=>$id,':e'=>$empresaId,':c'=>$clienteId]);$ag=$q->fetch(PDO::FETCH_ASSOC);if(!$ag)throw new RuntimeException('Agendamento não encontrado.');if(!in_array($ag['status'],['pendente','confirmado'],true)||new DateTimeImmutable()>=((new DateTimeImmutable($ag['inicio']))->modify('-2 hours')))throw new RuntimeException('O prazo para cancelar terminou. Alterações são permitidas até 2 horas antes.');$anterior=$ag['status'];$q=$pdo->prepare("UPDATE agendamentos SET status='cancelado' WHERE id=:id");$q->execute([':id'=>$id]);$q=$pdo->prepare("UPDATE agendamento_servicos SET status='cancelado' WHERE agendamento_id=:id");$q->execute([':id'=>$id]);$q=$pdo->prepare("INSERT INTO agendamento_historico(agendamento_id,status_anterior,status_novo,usuario_id,observacao) VALUES(:id,:ant,'cancelado',:u,'Agendamento cancelado pelo cliente.')");$q->execute([':id'=>$id,':ant'=>$anterior,':u'=>$usuarioId]);$pdo->commit();$_SESSION['csrf_autoagendamento']=bin2hex(random_bytes(32));out(['ok'=>true,'mensagem'=>'Agendamento cancelado com sucesso.','csrf_token'=>$_SESSION['csrf_autoagendamento']]);}
 if($a==='reagendar'){if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'mensagem'=>'Método não permitido.'],405);$csrf=(string)($_POST['csrf_token']??'');$ss=(string)($_SESSION['csrf_autoagendamento']??'');if(!$csrf||!$ss||!hash_equals($ss,$csrf))out(['ok'=>false,'mensagem'=>'Token CSRF inválido.'],403);$id=(int)($_POST['agendamento_id']??0);$s=(int)($_POST['servico_id']??0);$pr=(int)($_POST['profissional_id']??0);$d=trim((string)($_POST['data']??''));$h=trim((string)($_POST['hora']??''));if(!$id||!$s||!$pr||!dv($d)||!preg_match('/^\d{2}:\d{2}$/',$h))out(['ok'=>false,'mensagem'=>'Dados inválidos.'],422);$pdo->beginTransaction();$q=$pdo->prepare("SELECT inicio,status FROM agendamentos WHERE id=:id AND empresa_id=:e AND cliente_id=:c FOR UPDATE");$q->execute([':id'=>$id,':e'=>$empresaId,':c'=>$clienteId]);$ag=$q->fetch(PDO::FETCH_ASSOC);if(!$ag)throw new RuntimeException('Agendamento não encontrado.');if(!in_array($ag['status'],['pendente','confirmado'],true)||new DateTimeImmutable()>=((new DateTimeImmutable($ag['inicio']))->modify('-2 hours')))throw new RuntimeException('O prazo para reagendar terminou. Alterações são permitidas até 2 horas antes.');$sv=dadosServico($pdo,$empresaId,$s,$pr);if(!$sv)throw new RuntimeException('Serviço ou profissional indisponível.');$es=null;foreach(slots($pdo,$empresaId,$s,$pr,$d,$id) as $x)if($x['hora']===$h){$es=$x;break;}if(!$es)throw new RuntimeException('Este horário não está mais disponível.');$ant=$ag['status'];$old=(new DateTimeImmutable($ag['inicio']))->format('d/m/Y H:i');$q=$pdo->prepare("UPDATE agendamentos SET inicio=:i,fim=:f,status='pendente',valor_total=:v WHERE id=:id");$q->execute([':i'=>$es['inicio'],':f'=>$es['fim'],':v'=>$sv['preco'],':id'=>$id]);$q=$pdo->prepare("UPDATE agendamento_servicos SET servico_id=:s,profissional_id=:pr,status='agendado',inicio=:i,fim=:f,duracao_minutos=:du,valor=:v WHERE agendamento_id=:id AND ordem=1");$q->execute([':s'=>$s,':pr'=>$pr,':i'=>$es['inicio'],':f'=>$es['fim'],':du'=>$sv['duracao'],':v'=>$sv['preco'],':id'=>$id]);$q=$pdo->prepare("INSERT INTO agendamento_historico(agendamento_id,status_anterior,status_novo,usuario_id,observacao) VALUES(:id,:ant,'pendente',:u,:obs)");$q->execute([':id'=>$id,':ant'=>$ant,':u'=>$usuarioId,':obs'=>"Agendamento reagendado pelo cliente. Horário anterior: $old."]);$pdo->commit();$_SESSION['csrf_autoagendamento']=bin2hex(random_bytes(32));out(['ok'=>true,'mensagem'=>'Agendamento reagendado com sucesso!','csrf_token'=>$_SESSION['csrf_autoagendamento']]);}
 if($a==='confirmar'){if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'mensagem'=>'Método não permitido.'],405);$csrf=(string)($_POST['csrf_token']??'');$ss=(string)($_SESSION['csrf_autoagendamento']??'');if(!$csrf||!$ss||!hash_equals($ss,$csrf))out(['ok'=>false,'mensagem'=>'Token CSRF inválido.'],403);$s=(int)($_POST['servico_id']??0);$pr=(int)($_POST['profissional_id']??0);$d=trim((string)($_POST['data']??''));$h=trim((string)($_POST['hora']??''));if(!$s||!$pr||!dv($d)||!preg_match('/^\d{2}:\d{2}$/',$h))out(['ok'=>false,'mensagem'=>'Dados inválidos.'],422);
  $pdo->beginTransaction();$q=$pdo->prepare('SELECT id FROM profissionais WHERE id=:pr AND empresa_id=:e AND ativo=1 FOR UPDATE');$q->execute([':pr'=>$pr,':e'=>$empresaId]);if(!$q->fetchColumn())throw new RuntimeException('Profissional indisponível.');$sv=dadosServico($pdo,$empresaId,$s,$pr);if(!$sv)throw new RuntimeException('Serviço indisponível.');$es=null;foreach(slots($pdo,$empresaId,$s,$pr,$d) as $x)if($x['hora']===$h){$es=$x;break;}if(!$es)throw new RuntimeException('Este horário não está mais disponível.');
  $q=$pdo->prepare("INSERT INTO agendamentos(empresa_id,cliente_id,inicio,fim,status,origem,valor_total,criado_por_usuario_id) VALUES(:e,:c,:i,:f,'pendente','site',:v,:u)");$q->execute([':e'=>$empresaId,':c'=>$clienteId,':i'=>$es['inicio'],':f'=>$es['fim'],':v'=>$sv['preco'],':u'=>$usuarioId]);$id=(int)$pdo->lastInsertId();
  $q=$pdo->prepare("INSERT INTO agendamento_servicos(agendamento_id,servico_id,profissional_id,status,inicio,fim,duracao_minutos,valor,ordem) VALUES(:a,:s,:pr,'agendado',:i,:f,:d,:v,1)");$q->execute([':a'=>$id,':s'=>$s,':pr'=>$pr,':i'=>$es['inicio'],':f'=>$es['fim'],':d'=>$sv['duracao'],':v'=>$sv['preco']]);
  $q=$pdo->prepare("INSERT INTO agendamento_historico(agendamento_id,status_anterior,status_novo,usuario_id,observacao) VALUES(:a,NULL,'pendente',:u,'Agendamento realizado pelo cliente.')");$q->execute([':a'=>$id,':u'=>$usuarioId]);$pdo->commit();$_SESSION['csrf_autoagendamento']=bin2hex(random_bytes(32));out(['ok'=>true,'mensagem'=>'Agendamento realizado com sucesso!','csrf_token'=>$_SESSION['csrf_autoagendamento']]);}
 out(['ok'=>false,'mensagem'=>'Ação inválida.'],400);
}catch(RuntimeException $x){if($pdo->inTransaction())$pdo->rollBack();out(['ok'=>false,'mensagem'=>$x->getMessage()],409);}catch(Throwable $x){if($pdo->inTransaction())$pdo->rollBack();error_log($x->getMessage());out(['ok'=>false,'mensagem'=>'Não foi possível concluir o agendamento agora.'],500);}
