<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/db.php';exigirAdministrador();
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('Método não permitido.');}
$empresaId=(int)$_SESSION['empresa_id'];$pdo=getDB();$acao=trim((string)($_POST['acao']??''));
function listaC():never{header('Location: ../clientes.php');exit;} function cadC(?int $id=null):never{header('Location: ../cadastro-cliente-admin.php'.($id?'?editar='.$id:''));exit;}
function flC($t,$m,$e=[],$o=[]){$_SESSION['flash_cliente_admin']=['tipo'=>$t,'mensagem'=>$m,'erros'=>$e,'old'=>$o];} function flLC($t,$m){$_SESSION['flash_lista_clientes']=['tipo'=>$t,'mensagem'=>$m];}
function digsC($v){return preg_replace('/\D+/','',(string)$v)??'';} function cpfC($v){$c=digsC($v);if($c==='')return true;if(strlen($c)!==11||preg_match('/^(\d)\1{10}$/',$c))return false;for($t=9;$t<11;$t++){$s=0;for($i=0;$i<$t;$i++)$s+=(int)$c[$i]*(($t+1)-$i);if((int)$c[$t]!==((10*$s)%11)%10)return false;}return true;} function fmtC($v){$d=digsC($v);return $d===''?null:substr($d,0,3).'.'.substr($d,3,3).'.'.substr($d,6,3).'-'.substr($d,9,2);}
$csrf=(string)($_POST['csrf_token']??'');$sess=$acao==='alternar_status'?(string)($_SESSION['csrf_clientes']??''):(string)($_SESSION['csrf_cadastro_cliente_admin']??'');if($sess===''||$csrf===''||!hash_equals($sess,$csrf)){http_response_code(403);exit('Token CSRF inválido.');}
if($acao==='alternar_status'){$id=filter_input(INPUT_POST,'cliente_id',FILTER_VALIDATE_INT);$s=$pdo->prepare('SELECT id,pessoa_id,ativo FROM clientes WHERE id=:id AND empresa_id=:e LIMIT 1');$s->execute([':id'=>$id,':e'=>$empresaId]);$c=$s->fetch(PDO::FETCH_ASSOC);if(!$c){flLC('danger','Cliente não encontrado.');listaC();}$novo=(int)$c['ativo']===1?0:1;try{$pdo->beginTransaction();$s=$pdo->prepare('UPDATE clientes SET ativo=:a WHERE id=:id AND empresa_id=:e');$s->execute([':a'=>$novo,':id'=>$id,':e'=>$empresaId]);$s=$pdo->prepare('UPDATE pessoas SET ativo=:a WHERE id=:id AND empresa_id=:e');$s->execute([':a'=>$novo,':id'=>(int)$c['pessoa_id'],':e'=>$empresaId]);$pdo->commit();}catch(Throwable $x){if($pdo->inTransaction())$pdo->rollBack();flLC('danger','Não foi possível alterar o status.');listaC();}$_SESSION['csrf_clientes']=bin2hex(random_bytes(32));flLC('success',$novo?'Cliente ativado com sucesso.':'Cliente desativado com sucesso.');listaC();}
if(!in_array($acao,['criar','atualizar'],true)){http_response_code(400);exit('Ação inválida.');}
$id=null;$atual=null;if($acao==='atualizar'){$id=filter_input(INPUT_POST,'cliente_id',FILTER_VALIDATE_INT);$s=$pdo->prepare('SELECT c.pessoa_id,c.usuario_id,p.cpf FROM clientes c INNER JOIN pessoas p ON p.id=c.pessoa_id AND p.empresa_id=c.empresa_id WHERE c.id=:id AND c.empresa_id=:e LIMIT 1');$s->execute([':id'=>$id,':e'=>$empresaId]);$atual=$s->fetch(PDO::FETCH_ASSOC);if(!$atual){flLC('danger','Cliente não encontrado.');listaC();}}
$nome=trim((string)($_POST['nome_completo']??''));$cpfRaw=$acao==='atualizar'?(string)($atual['cpf']??''):trim((string)($_POST['cpf']??''));$nasc=trim((string)($_POST['data_nascimento']??''));$gen=trim((string)($_POST['genero']??'nao_informado'));$email=mb_strtolower(trim((string)($_POST['email']??'')));$tel=trim((string)($_POST['telefone']??''));$wa=isset($_POST['whatsapp'])?1:0;$cep=trim((string)($_POST['cep']??''));$log=trim((string)($_POST['logradouro']??''));$num=trim((string)($_POST['numero']??''));$comp=trim((string)($_POST['complemento']??''));$bairro=trim((string)($_POST['bairro']??''));$cidade=trim((string)($_POST['cidade']??''));$uf=mb_strtoupper(trim((string)($_POST['estado']??'')));$obs=trim((string)($_POST['observacoes']??''));$ativo=isset($_POST['ativo'])?1:0;
$old=['nome_completo'=>$nome,'cpf'=>$cpfRaw,'data_nascimento'=>$nasc,'genero'=>$gen,'email'=>$email,'telefone'=>$tel,'whatsapp'=>$wa,'cep'=>$cep,'logradouro'=>$log,'numero'=>$num,'complemento'=>$comp,'bairro'=>$bairro,'cidade'=>$cidade,'estado'=>$uf,'observacoes'=>$obs,'ativo'=>$ativo];$err=[];
if($nome==='')$err['nome_completo']='Informe o nome completo.';if(!cpfC($cpfRaw))$err['cpf']='Informe um CPF válido.';$cpf=fmtC($cpfRaw);if($nasc!==''){$d=DateTimeImmutable::createFromFormat('!Y-m-d',$nasc);if(!$d||$d->format('Y-m-d')!==$nasc||$d>new DateTimeImmutable('today'))$err['data_nascimento']='Informe uma data válida.';}if(!in_array($gen,['masculino','feminino','nao_binario','nao_informado'],true))$err['genero']='Gênero inválido.';if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$err['email']='Informe um e-mail válido.';if($tel!==''&&(strlen(digsC($tel))<10||strlen(digsC($tel))>11))$err['telefone']='Informe um telefone válido.';if($tel===''&&$wa)$err['telefone']='Informe o telefone antes de marcar WhatsApp.';
if($acao==='atualizar'&&!empty($atual['usuario_id'])){$s=$pdo->prepare('SELECT email FROM usuarios WHERE id=:id');$s->execute([':id'=>(int)$atual['usuario_id']]);if(mb_strtolower((string)$s->fetchColumn())!==$email)$err['email']='O e-mail está vinculado à conta de acesso e não pode ser alterado.';}
if($cpf&&!isset($err['cpf'])){$sql='SELECT id FROM pessoas WHERE empresa_id=:e AND cpf=:cpf';$p=[':e'=>$empresaId,':cpf'=>$cpf];if($acao==='atualizar'){$sql.=' AND id<>:p';$p[':p']=(int)$atual['pessoa_id'];}$s=$pdo->prepare($sql.' LIMIT 1');$s->execute($p);if($s->fetchColumn())$err['cpf']='Já existe uma pessoa com este CPF nesta empresa.';}
if($err){flC('danger','Revise os campos destacados.',$err,$old);cadC($id);}
try{$pdo->beginTransaction();if($acao==='criar'){$s=$pdo->prepare('INSERT INTO pessoas (empresa_id,nome_completo,cpf,data_nascimento,genero,email,ativo) VALUES (:e,:n,:cpf,:dn,:g,:em,:a)');$s->execute([':e'=>$empresaId,':n'=>$nome,':cpf'=>$cpf,':dn'=>$nasc?:null,':g'=>$gen,':em'=>$email?:null,':a'=>$ativo]);$pid=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO clientes (empresa_id,pessoa_id,usuario_id,observacoes,ativo) VALUES (:e,:p,NULL,:o,:a)');$s->execute([':e'=>$empresaId,':p'=>$pid,':o'=>$obs?:null,':a'=>$ativo]);$id=(int)$pdo->lastInsertId();}else{$pid=(int)$atual['pessoa_id'];$s=$pdo->prepare('UPDATE pessoas SET nome_completo=:n,data_nascimento=:dn,genero=:g,email=:em,ativo=:a WHERE id=:p AND empresa_id=:e');$s->execute([':n'=>$nome,':dn'=>$nasc?:null,':g'=>$gen,':em'=>$email?:null,':a'=>$ativo,':p'=>$pid,':e'=>$empresaId]);$s=$pdo->prepare('UPDATE clientes SET observacoes=:o,ativo=:a WHERE id=:id AND empresa_id=:e');$s->execute([':o'=>$obs?:null,':a'=>$ativo,':id'=>$id,':e'=>$empresaId]);}
$s=$pdo->prepare('SELECT id FROM telefones_pessoa WHERE pessoa_id=:p ORDER BY principal DESC,id LIMIT 1');$s->execute([':p'=>$pid]);$tid=$s->fetchColumn();if($tel!==''){if($tid){$s=$pdo->prepare('UPDATE telefones_pessoa SET numero=:n,tipo="celular",whatsapp=:w,principal=1 WHERE id=:id AND pessoa_id=:p');$s->execute([':n'=>$tel,':w'=>$wa,':id'=>$tid,':p'=>$pid]);}else{$s=$pdo->prepare('INSERT INTO telefones_pessoa (pessoa_id,numero,tipo,whatsapp,principal) VALUES (:p,:n,"celular",:w,1)');$s->execute([':p'=>$pid,':n'=>$tel,':w'=>$wa]);}}elseif($tid){$s=$pdo->prepare('DELETE FROM telefones_pessoa WHERE id=:id AND pessoa_id=:p');$s->execute([':id'=>$tid,':p'=>$pid]);}
$tem=$cep!==''||$log!==''||$num!==''||$comp!==''||$bairro!==''||$cidade!==''||$uf!=='';if($tem){$s=$pdo->prepare('INSERT INTO enderecos_pessoa (pessoa_id,cep,logradouro,numero,complemento,bairro,cidade,estado) VALUES (:p,:cep,:l,:n,:c,:b,:cid,:uf) ON DUPLICATE KEY UPDATE cep=VALUES(cep),logradouro=VALUES(logradouro),numero=VALUES(numero),complemento=VALUES(complemento),bairro=VALUES(bairro),cidade=VALUES(cidade),estado=VALUES(estado)');$s->execute([':p'=>$pid,':cep'=>$cep?:null,':l'=>$log?:null,':n'=>$num?:null,':c'=>$comp?:null,':b'=>$bairro?:null,':cid'=>$cidade?:null,':uf'=>$uf?:null]);}else{$s=$pdo->prepare('DELETE FROM enderecos_pessoa WHERE pessoa_id=:p');$s->execute([':p'=>$pid]);}$pdo->commit();}catch(Throwable $x){if($pdo->inTransaction())$pdo->rollBack();error_log('Erro cliente admin: '.$x->getMessage());flC('danger','Não foi possível salvar o cliente agora.',[],$old);cadC($id);}
$_SESSION['csrf_cadastro_cliente_admin']=bin2hex(random_bytes(32));flLC('success',$acao==='criar'?'Cliente cadastrado com sucesso.':'Cliente atualizado com sucesso.');listaC();
