<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/db.php';exigirAdministrador();
$empresa=(int)$_SESSION['empresa_id'];$pdo=getDB();
if(empty($_SESSION['csrf_ausencias_colaboradores']))$_SESSION['csrf_ausencias_colaboradores']=bin2hex(random_bytes(32));$csrf=(string)$_SESSION['csrf_ausencias_colaboradores'];
$ok=(string)($_SESSION['flash_success_ausencias_colaboradores']??'');$erro=(string)($_SESSION['flash_error_ausencias_colaboradores']??'');unset($_SESSION['flash_success_ausencias_colaboradores'],$_SESSION['flash_error_ausencias_colaboradores']);
$st=$pdo->prepare("SELECT s.*,p.nome_completo colaborador_nome FROM colaborador_solicitacoes_ausencia s INNER JOIN colaboradores c ON c.id=s.colaborador_id AND c.empresa_id=s.empresa_id INNER JOIN pessoas p ON p.id=c.pessoa_id AND p.empresa_id=s.empresa_id WHERE s.empresa_id=:e ORDER BY FIELD(s.status,'pendente','aprovada','rejeitada','cancelada'),s.inicio");$st->execute([':e'=>$empresa]);$lista=$st->fetchAll(PDO::FETCH_ASSOC);
$id=filter_input(INPUT_GET,'detalhe',FILTER_VALIDATE_INT);$det=null;$hist=[];$coment=[];
if(is_int($id)){foreach($lista as$x)if((int)$x['id']===$id){$det=$x;break;}if($det){$st=$pdo->prepare("SELECT h.*,COALESCE(adm.nome_completo,pc.nome_completo,u.email) usuario_nome FROM colaborador_solicitacao_ausencia_historico h INNER JOIN usuarios u ON u.id=h.usuario_id LEFT JOIN administradores adm ON adm.usuario_id=u.id AND adm.empresa_id=:e LEFT JOIN colaboradores col ON col.usuario_id=u.id AND col.empresa_id=:e LEFT JOIN pessoas pc ON pc.id=col.pessoa_id AND pc.empresa_id=:e WHERE h.solicitacao_id=:id ORDER BY h.criado_em,h.id");$st->execute([':e'=>$empresa,':id'=>$id]);$hist=$st->fetchAll(PDO::FETCH_ASSOC);$st=$pdo->prepare("SELECT c.*,COALESCE(adm.nome_completo,u.email) usuario_nome FROM colaborador_solicitacao_ausencia_comentarios c INNER JOIN usuarios u ON u.id=c.usuario_id LEFT JOIN administradores adm ON adm.usuario_id=u.id AND adm.empresa_id=:e WHERE c.solicitacao_id=:id ORDER BY c.criado_em,c.id");$st->execute([':e'=>$empresa,':id'=>$id]);$coment=$st->fetchAll(PDO::FETCH_ASSOC);}}
function caf(string$d):string{return(new DateTimeImmutable($d))->format('d/m/Y H:i');}function cas(string$s):string{return match($s){'pendente'=>'Pendente','aprovada'=>'Aprovada','rejeitada'=>'Rejeitada','cancelada'=>'Cancelada',default=>$s};}
$pageTitle='Ausências de colaboradores';$pageCss='ausencias-profissionais.css?v=20260915-1';require __DIR__.'/partials/header.php';require __DIR__.'/partials/sidebar.php';require __DIR__.'/partials/navbar.php';?>
<main class="app-content"><div class="app-page-header"><h1>Ausências de colaboradores</h1><p>Analise solicitações de ausência dos colaboradores e mantenha o histórico das decisões.</p></div>
<?php if($ok):?><div class="alert alert-success"><?=htmlspecialchars($ok,ENT_QUOTES,'UTF-8')?></div><?php endif;if($erro):?><div class="alert alert-danger"><?=htmlspecialchars($erro,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<section class="app-card mb-4"><div class="app-card-header"><h2>Solicitações</h2></div><div class="app-card-body p-0"><?php if(!$lista):?><div class="app-empty-state"><p>Nenhuma solicitação encontrada.</p></div><?php else:?><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Colaborador</th><th>Período</th><th>Tipo</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($lista as$s):?><tr><td><?=htmlspecialchars((string)$s['colaborador_nome'],ENT_QUOTES,'UTF-8')?></td><td><?=caf((string)$s['inicio'])?> – <?=caf((string)$s['fim'])?></td><td><?=htmlspecialchars((string)$s['tipo'],ENT_QUOTES,'UTF-8')?></td><td class="ausencia-status ausencia-status--<?=$s['status']?>"><?=cas((string)$s['status'])?></td><td><a class="btn btn-sm btn-outline-primary" href="?detalhe=<?=(int)$s['id']?>">Detalhes</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></section>
<?php if($det):?><section class="app-card"><div class="app-card-header"><h2>Detalhes #<?=(int)$det['id']?></h2></div><div class="app-card-body"><p><strong>Colaborador:</strong> <?=htmlspecialchars((string)$det['colaborador_nome'],ENT_QUOTES,'UTF-8')?><br><strong>Período:</strong> <?=caf((string)$det['inicio'])?> – <?=caf((string)$det['fim'])?><br><strong>Status:</strong> <?=cas((string)$det['status'])?><br><strong>Motivo:</strong> <?=htmlspecialchars((string)($det['motivo']?:'—'),ENT_QUOTES,'UTF-8')?></p>
<?php if($det['status']==='pendente'):?><form method="post" action="api/ausencias-colaboradores.php"><input type="hidden" name="csrf_token" value="<?=$csrf?>"><input type="hidden" name="solicitacao_id" value="<?=(int)$det['id']?>"><div class="form-group"><label>Observação da decisão</label><textarea name="observacao_decisao" class="form-control"></textarea></div><button name="acao" value="aprovar" class="btn btn-success">Aprovar</button> <button name="acao" value="rejeitar" class="btn btn-outline-danger">Rejeitar</button></form><?php elseif($det['status']==='aprovada'):?><form method="post" action="api/ausencias-colaboradores.php"><input type="hidden" name="csrf_token" value="<?=$csrf?>"><input type="hidden" name="acao" value="cancelar_aprovacao"><input type="hidden" name="solicitacao_id" value="<?=(int)$det['id']?>"><div class="form-group"><label>Motivo para cancelar a aprovação</label><textarea name="motivo_cancelamento" class="form-control" required></textarea></div><button class="btn btn-outline-danger">Cancelar aprovação</button></form><?php endif;?>
<h3 class="h5 mt-4">Histórico</h3><ul class="ausencia-timeline"><?php foreach($hist as$h):?><li><strong><?=htmlspecialchars(str_replace('_',' ',(string)$h['acao']),ENT_QUOTES,'UTF-8')?></strong><small><?=htmlspecialchars((string)$h['usuario_nome'].' • '.caf((string)$h['criado_em']),ENT_QUOTES,'UTF-8')?></small><?php if($h['detalhes']):?><div><?=nl2br(htmlspecialchars((string)$h['detalhes'],ENT_QUOTES,'UTF-8'))?></div><?php endif;?></li><?php endforeach;?></ul>
<h3 class="h5 mt-4">Comentários internos</h3><?php foreach($coment as$c):?><div class="ausencia-comment"><strong><?=htmlspecialchars((string)$c['usuario_nome'],ENT_QUOTES,'UTF-8')?></strong> <small><?=caf((string)$c['criado_em'])?></small><div><?=nl2br(htmlspecialchars((string)$c['comentario'],ENT_QUOTES,'UTF-8'))?></div></div><?php endforeach;?><form method="post" action="api/ausencias-colaboradores.php" class="mt-3"><input type="hidden" name="csrf_token" value="<?=$csrf?>"><input type="hidden" name="acao" value="comentar"><input type="hidden" name="solicitacao_id" value="<?=(int)$det['id']?>"><textarea name="comentario" class="form-control mb-2" required></textarea><button class="btn btn-outline-primary">Adicionar comentário</button></form></div></section><?php endif;?></main><?php require __DIR__.'/partials/footer.php';?>
