<?php

declare(strict_types=1); session_start(); require_once __DIR__.'/../includes/cliente-auth.php';
$clientId=(string)getenv('GOOGLE_CLIENT_ID');$clientSecret=(string)getenv('GOOGLE_CLIENT_SECRET');$redirectUri=(string)(getenv('GOOGLE_REDIRECT_URI')?:'http://localhost:8096/callback.php');$pdo=getDB();$action=(string)($_GET['action']??'');
function googleErro(string $slug=''): never{$u='login-cliente.php'.($slug!==''?'?empresa='.rawurlencode($slug).'&erro=google':'?erro=google');header('Location: '.$u);exit;}
if($clientId===''||$clientSecret===''){error_log('Google OAuth não configurado.');googleErro((string)($_GET['empresa']??''));}
if($action==='auth'){$slug=trim((string)($_GET['empresa']??''));$empresa=clienteEmpresaPorSlug($pdo,$slug);if(!$empresa){http_response_code(404);exit('Empresa não encontrada.');}$state=bin2hex(random_bytes(32));$_SESSION['google_oauth_cliente']=['state'=>$state,'empresa_id'=>(int)$empresa['id'],'empresa_slug'=>(string)$empresa['slug'],'criado_em'=>time()];$url='https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(['client_id'=>$clientId,'redirect_uri'=>$redirectUri,'response_type'=>'code','scope'=>'openid email profile','access_type'=>'online','prompt'=>'select_account','state'=>$state]);header('Location: '.$url);exit;}
if(isset($_GET['error'])){$s=(string)($_SESSION['google_oauth_cliente']['empresa_slug']??'');unset($_SESSION['google_oauth_cliente']);googleErro($s);}if(!isset($_GET['code'],$_GET['state']))googleErro();$o=$_SESSION['google_oauth_cliente']??null;if(!is_array($o)||empty($o['state'])||!hash_equals((string)$o['state'],(string)$_GET['state'])||(int)($o['criado_em']??0)<time()-600){$s=is_array($o)?(string)($o['empresa_slug']??''):'';unset($_SESSION['google_oauth_cliente']);googleErro($s);} $slug=(string)$o['empresa_slug'];$empresa=clienteEmpresaPorSlug($pdo,$slug);unset($_SESSION['google_oauth_cliente']);if(!$empresa||(int)$empresa['id']!==(int)$o['empresa_id'])googleErro($slug);
try{$ch=curl_init('https://oauth2.googleapis.com/token');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['code'=>(string)$_GET['code'],'client_id'=>$clientId,'client_secret'=>$clientSecret,'redirect_uri'=>$redirectUri,'grant_type'=>'authorization_code']),CURLOPT_TIMEOUT=>15]);$resp=curl_exec($ch);$http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($resp===false||$http<200||$http>=300)throw new RuntimeException('Falha token Google.');$tok=json_decode((string)$resp,true);if(empty($tok['access_token']))throw new RuntimeException('Token ausente.');$ch=curl_init('https://www.googleapis.com/oauth2/v2/userinfo');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$tok['access_token']],CURLOPT_TIMEOUT=>15]);$resp=curl_exec($ch);$http=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($resp===false||$http<200||$http>=300)throw new RuntimeException('Falha perfil Google.');$g=json_decode((string)$resp,true);$gid=trim((string)($g['id']??''));$email=mb_strtolower(trim((string)($g['email']??'')));$nome=trim((string)($g['name']??''));$foto=trim((string)($g['picture']??''));if($gid===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!(bool)($g['verified_email']??false))throw new RuntimeException('Google sem e-mail verificado.');$stmt=$pdo->prepare('SELECT id,email,google_id,ativo FROM usuarios WHERE google_id=:gid OR email=:email ORDER BY CASE WHEN google_id=:gid2 THEN 0 ELSE 1 END LIMIT 1');$stmt->execute([':gid'=>$gid,':email'=>$email,':gid2'=>$gid]);$u=$stmt->fetch(PDO::FETCH_ASSOC);if($u){if((int)$u['ativo']!==1)throw new RuntimeException('Conta desativada.');if(!empty($u['google_id'])&&(string)$u['google_id']!==$gid)throw new RuntimeException('E-mail ligado a outro Google.');$uid=(int)$u['id'];if(empty($u['google_id'])){$stmt=$pdo->prepare('UPDATE usuarios SET google_id=:gid,foto_url=COALESCE(:foto,foto_url) WHERE id=:id');$stmt->execute([':gid'=>$gid,':foto'=>$foto?:null,':id'=>$uid]);}$c=clienteBuscarVinculo($pdo,$uid,(int)$empresa['id']);if($c){if((int)$c['cliente_ativo']!==1||(int)$c['pessoa_ativa']!==1)throw new RuntimeException('Cliente desativado.');clienteIniciarSessao($pdo,['id'=>$uid,'email'=>$email],$c,$empresa);header('Location: dashboard-cliente.php');exit;}$_SESSION['cliente_cadastro_pendente']=['origem'=>'google','usuario_id'=>$uid,'email'=>$email,'nome'=>$nome,'google_id'=>$gid,'foto_url'=>$foto?:null,'empresa_id'=>(int)$empresa['id'],'empresa_slug'=>$slug];}else{$_SESSION['cliente_cadastro_pendente']=['origem'=>'google','usuario_id'=>0,'email'=>$email,'nome'=>$nome,'google_id'=>$gid,'foto_url'=>$foto?:null,'empresa_id'=>(int)$empresa['id'],'empresa_slug'=>$slug];}header('Location: completar-cadastro-cliente.php?empresa='.rawurlencode($slug));exit;}catch(Throwable $e){error_log('Erro OAuth cliente: '.$e->getMessage());googleErro($slug);}
